### ISSUE TITLE
FSTSW/FNSTSW store x87 FPU instruction bad decode

### ISSUE THREAD

**Issue by BigJim** [vmt/udis86#39] opened 2013-05-17 10:06 UTC
udis86 doesn't do proper decoding for most if not all "fstsw" a "fstcw" 32bit instructions.
Example:
I decode ""fstsw ax" (bytes 9B DF E0) the decoder says it's just one byte in size and the text "wait" is returned by "ud_insn_asm()"

Oddly this must be a particularly tricky thing to decode because I have not seen one dissembler get it right For example the same problem exists in BeaEngine (where I also submitted this issue several months ago with no response yet).

P.S. udis86 (despite this issue) seems to be one of the, if not the most, complete around.

**Comment by vmt** [comment] 2013-05-18 18:03
Hi BigJim, Technically this is not a bug. From the intel documentation:

> The assembler issues two instructions for the FSTSW instruction
> (an FWAIT instruction followed by an FNSTSW instruction), and the
> processor executes each of these instructions separately. If an
> exception is generated for either of these instructions, the save
> EIP points to the instruction that caused the exception.

Which is what udis86 does:

```
$ echo "9b df e0" | ./udcli/udcli -x
0000000000000000 9b               wait
0000000000000001 dfe0             fnstsw ax
```

From the standpoint of someone using the library to decode the stream of bytes, the right thing to do is to issue the two separate instructions, as the processor would. What do you think?

**Comment by BigJim** [comment] 2013-05-20 12:43
I see thanks. Agreed it's not a issue, more of a "bug" in my understanding.
It makes a lot of sense and explains why the other similar engines decode the same.
I was using the IDA Pro dissembler as a reference. It combines these to display just the FSTxx instruction alone.

I'm sure what one can do is just special case externally. Any time this single byte "wait" is encountered, look at the next instruction for a FSTxx.  Or just modify the code to do this internally.

**Comment by clevcode** [comment] 2013-05-20 13:40
BigJim,

Since it is in fact two separate instructions, I don't think this could be
considered a bug.

Since the CPU executes each instruction separately, and since the saved EIP
would point to the instruction causing the exception, I think it makes more
sense to disassemble it to two separate instructions. In some cases, such
as if one is using udis86 as the disassembler in an emulator/simulator, or
if you are overwriting code / injecting hooks and use udis86 to keep track
of instruction boundaries for borrowed bytes, this could be of practical
significance.

When it comes to just disassembling for the purpose of reading the
disassembled code, combining them could possibly be helpful. If this is
implemented in udis86 I think it should be optional though, and of course,
it can easily be added as special cases in case you're using the udis86
engine for disassembling purposes and prefer using the
fstsw/fstcw-mnemonics. I'm personally fine with always treating them as
separate instructions though.

Cheers,
Joel Eriksson
ClevCode

**Comment by vmt** [comment] 2013-05-27 02:01
I'd like to keep the specializations to a minimum. Closing this for now.

**Closed as completed by vmt** 2013-05-27 02:01 UTC
